version: "3.3"
services:
  backend:
    image: node:16-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000

  component:
    image: node:16-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run watch"
    volumes:
      - ./component:/usr/src/app
    expose:
      - 3000

  frontend:
    image: node:16-alpine
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run start"
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 4200:4200
