# .github/workflows/main.yml
# Copy/pasted from https://angular.io/guide/testing#configure-project-for-github-actions
name: CI Nest.js app through Github Actions
on: push
jobs:
  backend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup
        working-directory: backend
        run: npm ci

      - name: Test
        working-directory: backend
        run: npm test


      # - name: E2E Test
      #   run: |
      #     npm test:e2e

  kanban-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci
        working-directory: kanban

      - name: Test
        working-directory: kanban
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Setup
        run: npm ci
        working-directory: frontend

      - name: Test
        working-directory: frontend
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
